export const WordsForca = [{
    dica: "Animais",
    Words:[
        "Albatroz","Alpaca",
        "Anchova", "Bacalhau",
        "Badejo", "Barracuda","Beluga",
        "Cagado","Chinchila","Craca",
        "Dromedario","Escaravelho",
        "Gerbo","Gnu",
        "Gralha","Hamster",
        "Lemure","Lhama",
        "Lince","Marreco",
        "Melro","Ocapi",
        "Ourico","Pelicano",
        "Percevejo","Pirilampo",
        "Quati","Rouxinol",
        "Sanguessuga","Surucucu",
        "Tapir","Texugo",
        "Vison","Zebu"]
},
{
    dica:"Profissão",
    Words:["Apicultor",
        "Agrônomo",
        "Auditor",
        "Bartender",
        "Cerimonialista",
        "Chef",
        "Coach",
        "Desembargador",
        "Despachante",
        "Endocrinologista",
        "Embaixador",
        "Gerentólogo",
        "Headhunter",
        "Intérprete",
        "Juiz",
        "Nanotecnólogo",
        "Nutrólogo",
        "Pizzaiolo",
        "Perito",
        "Quiroprata",
        "Roteirizador",
        "Silvicultor",
        "Trader",
        "Taquígrafo",
        "Turismólogo",]
}]
